// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	AccountID int32     `json:"account_id"`
	Post      string    `json:"post"`
	Nickname  string    `json:"nickname"`
	Password  string    `json:"password"`
	Phone     string    `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
}

type Cheque struct {
	ChequeID  int32         `json:"cheque_id"`
	Price     int32         `json:"price"`
	PayMethod string        `json:"pay_method"`
	PayStatus string        `json:"pay_status"`
	CreatedAt time.Time     `json:"created_at"`
	OrdID     sql.NullInt64 `json:"ord_id"`
}

type Courier struct {
	CourierID int32  `json:"courier_id"`
	Title     string `json:"title"`
	Phone     string `json:"phone"`
}

type MenuItem struct {
	MenuID    int32     `json:"menu_id"`
	Title     string    `json:"title"`
	Category  string    `json:"category"`
	Price     int32     `json:"price"`
	CreatedAt time.Time `json:"created_at"`
}

type Ord struct {
	OrdID     int32         `json:"ord_id"`
	OrdDate   time.Time     `json:"ord_date"`
	CreatedAt time.Time     `json:"created_at"`
	AccountID sql.NullInt64 `json:"account_id"`
	CourierID sql.NullInt64 `json:"courier_id"`
}

type OrderItem struct {
	OrderItemID int32          `json:"order_item_id"`
	Title       sql.NullString `json:"title"`
	Price       int32          `json:"price"`
	CreatedAt   time.Time      `json:"created_at"`
	MenuID      sql.NullInt64  `json:"menu_id"`
	OrdID       sql.NullInt64  `json:"ord_id"`
}
