// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCheque(ctx context.Context, arg CreateChequeParams) (Cheque, error)
	CreateCourier(ctx context.Context, arg CreateCourierParams) (Courier, error)
	CreateMenu_item(ctx context.Context, arg CreateMenu_itemParams) (MenuItem, error)
	CreateOrd(ctx context.Context, arg CreateOrdParams) (Ord, error)
	CreateOrder_item(ctx context.Context, arg CreateOrder_itemParams) (OrderItem, error)
	DeleteAccount(ctx context.Context, accountID int32) error
	DeleteCheque(ctx context.Context, chequeID int32) error
	DeleteCourier(ctx context.Context, courierID int32) error
	DeleteMenu_item(ctx context.Context, menuID int32) error
	DeleteOrd(ctx context.Context, ordID int32) error
	DeleteOrder_item(ctx context.Context, orderItemID int32) error
	GetAccount(ctx context.Context, accountID int32) (Account, error)
	GetAccountForPassword(ctx context.Context, arg GetAccountForPasswordParams) (Account, error)
	GetCheque(ctx context.Context, chequeID int32) (Cheque, error)
	GetCourier(ctx context.Context, courierID int32) (Courier, error)
	GetMenu_item(ctx context.Context, menuID int32) (MenuItem, error)
	GetOrd(ctx context.Context, ordID int32) (Ord, error)
	GetOrder_item(ctx context.Context, orderItemID int32) (OrderItem, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListCheque(ctx context.Context, limit int32) ([]Cheque, error)
	ListCourier(ctx context.Context, arg ListCourierParams) ([]Courier, error)
	ListMenu_item(ctx context.Context, arg ListMenu_itemParams) ([]MenuItem, error)
	ListOrd(ctx context.Context, limit int32) ([]Ord, error)
	ListOrder_item(ctx context.Context, limit int32) ([]OrderItem, error)
}

var _ Querier = (*Queries)(nil)
